# Makefile for Bash Diamonds (Week 1 - lines)
# Debug-enabled, directory-safe.

PROJECT     := diamonds
BUILD_DIR   := build
SRC_DIR     := src
INCLUDE_DIR := src/include
TEST_DIR    := tests

# Point this at a Bash *source* tree (not just /usr/include/bash) if you want
# best compatibility when building loadable builtins.
# Override:
#   make BASH_SRC=/home/opsman/bash
BASH_SRC ?= /usr/include/bash

CC   ?= cc
GDB  ?= gdb
BASH ?= bash

WARN := -Wall -Wextra -Werror -Wpedantic
DEFS := -D_GNU_SOURCE

# Include paths:
# - diamondcore public headers
# - bash headers: some distros provide /usr/include/bash, while a bash source tree
#   has headers in its root plus include/ and builtins/
INCFLAGS := -I$(INCLUDE_DIR) \
            -I$(BASH_SRC) -I$(BASH_SRC)/include -I$(BASH_SRC)/builtins

CFLAGS_BASE  := $(WARN) $(DEFS) -fPIC -fvisibility=hidden -fno-common $(INCFLAGS)
LDFLAGS_BASE := -shared
LDLIBS       := -lm

# Week 1 builtins
BUILTINS := lines fields

# Core sources (includes opts.c; opts.c must not be empty under -Wpedantic/-Werror)
CORE_SRCS := $(wildcard $(SRC_DIR)/diamondcore/*.c)
CORE_OBJS := $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/obj/%.o,$(CORE_SRCS))

.PHONY: all debug clean test gdb-% run-%

all: debug

# --------------------------
# Debug build
# --------------------------
debug: CFLAGS := $(CFLAGS_BASE) -O0 -g3 -fno-omit-frame-pointer
debug: $(BUILD_DIR) $(BUILD_DIR)/obj \
       $(foreach b,$(BUILTINS),$(BUILD_DIR)/$(b).debug.so)

# Ensure directories exist
$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(BUILD_DIR)/obj:
	mkdir -p $(BUILD_DIR)/obj

# Compile diamondcore sources
$(BUILD_DIR)/obj/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)/obj
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c -o $@ $<

# Build builtin shared object
$(BUILD_DIR)/%.debug.so: $(SRC_DIR)/builtins/builtin_%.c $(CORE_OBJS) | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(LDFLAGS_BASE) -o $@ $^ $(LDLIBS)

# --------------------------
# Test runner
# --------------------------
test: debug
	@command -v bats >/dev/null 2>&1 || (echo "bats not found"; exit 2)
	BASH_BUILTINS_DIR="$(abspath $(BUILD_DIR))" bats $(TEST_DIR)

# --------------------------
# Run builtin (no gdb)
# Usage: make run-lines
# --------------------------
run-%: debug
	@$(BASH) --noprofile --norc -c 'enable -f "$(abspath $(BUILD_DIR))/$*.debug.so" $*; $* --help'

# --------------------------
# GDB debug session
# Usage: make gdb-lines
# --------------------------
gdb-%: debug
	@case "$*" in \
		lines|fields) ;; \
		*) echo "Unknown builtin '$*' (supported: $(BUILTINS))" >&2; exit 2 ;; \
	esac
	@rc="$(abspath $(BUILD_DIR))/rc_$*.sh"; \
	so="$(abspath $(BUILD_DIR))/$*.debug.so"; \
	printf '%s\n' \
		'# Auto-generated by make gdb-<builtin>' \
		'set -o pipefail' \
		'enable -f "'"$$so"'" '"$*"' || { echo "enable failed" >&2; exit 2; }' \
		'PS1="(gdb-'"$*"' )\u:\w\$ "' \
	> "$$rc"; \
	echo "Launching: $(GDB) --args $(BASH) --noprofile --norc --rcfile $$rc -i"; \
	exec $(GDB) --args $(BASH) --noprofile --norc --rcfile "$$rc" -i

# --------------------------
# Clean
# --------------------------
clean:
	rm -rf $(BUILD_DIR)
