#!/usr/bin/env bats
# tests/spec_release_pkg.bats

@test "release packaging: make dist emits tarball and checksum with required contents" {
  run bash -c '
    set -euo pipefail
    make dist-clean >/dev/null
    make dist >/dev/null
    tarball="$(ls -1t build/release/diamonds-*.tar.gz | head -n1)"
    [ -n "$tarball" ]
    [ -f "$tarball" ]
    [ -f "$tarball.sha256" ]
    sha256sum -c "$tarball.sha256" >/dev/null
    tar -tzf "$tarball" | grep -E "/builtins/lines\\.so$" >/dev/null
    tar -tzf "$tarball" | grep -E "/install-user\\.sh$" >/dev/null
    tar -tzf "$tarball" | grep -E "/docs/project-spec\\.md$" >/dev/null
    tar -tzf "$tarball" | grep -E "/README\\.md$" >/dev/null
  '
  [ "$status" -eq 0 ]
}

@test "release packaging: make dist is repeatable and refreshes artifact" {
  run bash -c '
    set -euo pipefail
    make dist-clean >/dev/null
    make dist >/dev/null
    tarball="$(ls -1t build/release/diamonds-*.tar.gz | head -n1)"
    before="$(stat -c %Y "$tarball")"
    sleep 1
    make dist >/dev/null
    after="$(stat -c %Y "$tarball")"
    [ "$after" -gt "$before" ]
  '
  [ "$status" -eq 0 ]
}

@test "release packaging: bundled installer runs with --help" {
  run bash -c '
    set -euo pipefail
    make dist-clean >/dev/null
    make dist >/dev/null
    tarball="$(ls -1t build/release/diamonds-*.tar.gz | head -n1)"
    tmpdir="$(mktemp -d)"
    trap "rm -rf \"$tmpdir\"" EXIT
    tar -C "$tmpdir" -xzf "$tarball"
    pkg_dir="$(find "$tmpdir" -mindepth 1 -maxdepth 1 -type d | head -n1)"
    [ -n "$pkg_dir" ]
    [ -x "$pkg_dir/install-user.sh" ]
    "$pkg_dir/install-user.sh" --help >/dev/null
  '
  [ "$status" -eq 0 ]
}

@test "release packaging: installer generates expected loader script" {
  run bash -c '
    set -euo pipefail
    tmpdir="$(mktemp -d)"
    trap "rm -rf \"$tmpdir\"" EXIT
    src_dir="$tmpdir/src"
    prefix_dir="$tmpdir/prefix dir"
    bashrc_file="$tmpdir/bashrc"
    mkdir -p "$src_dir"
    : > "$src_dir/sample.so"

    ./scripts/install-user.sh \
      --source "$src_dir" \
      --prefix "$prefix_dir" \
      --bashrc "$bashrc_file" \
      --no-rc >/dev/null

    cat > "$tmpdir/expected" <<EOF
#!/usr/bin/env bash
# Generated by Bash Diamonds install-user.sh
[ -n "\${BASH_VERSION:-}" ] || return 0
for so in "$prefix_dir"/*.so; do
  [ -f "\$so" ] || continue
  name="\${so##*/}"
  name="\${name%.so}"
  enable -f "\$so" "\$name" 2>/dev/null || true
done
EOF

    cmp -s "$tmpdir/expected" "$prefix_dir/load.sh"
    test ! -e "$bashrc_file"
  '
  [ "$status" -eq 0 ]
}

@test "release packaging: checksum validation fails when tarball is modified" {
  run bash -c '
    set -euo pipefail
    make dist-clean >/dev/null
    make dist >/dev/null
    tarball="$(ls -1t build/release/diamonds-*.tar.gz | head -n1)"
    printf "x" >> "$tarball"
    ! sha256sum -c "$tarball.sha256" >/dev/null 2>&1
  '
  [ "$status" -eq 0 ]
}
