#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: install-user.sh [OPTIONS]

Install Bash Diamonds builtins for the current user.

Options:
  --source DIR   Directory containing *.so files (default: auto-detect)
  --prefix DIR   Install prefix (default: $HOME/.local/lib/bash-diamonds)
  --bashrc FILE  Bash rc file to update (default: $HOME/.bashrc)
  --no-rc        Do not modify bashrc
  --help         Show this help and exit

Auto-detect source order:
  1) ./builtins   (release tarball layout)
  2) ./build      (repository layout after `make rel` or `make debug`)
EOF
}

die() {
  printf 'install-user.sh: %s\n' "$1" >&2
  exit 2
}

SOURCE_DIR=""
PREFIX_DIR="${HOME}/.local/lib/bash-diamonds"
BASHRC_FILE="${HOME}/.bashrc"
UPDATE_BASHRC=1

while (($# > 0)); do
  case "$1" in
    --source)
      shift
      (($# > 0)) || die "--source requires an argument"
      SOURCE_DIR="$1"
      ;;
    --prefix)
      shift
      (($# > 0)) || die "--prefix requires an argument"
      PREFIX_DIR="$1"
      ;;
    --bashrc)
      shift
      (($# > 0)) || die "--bashrc requires an argument"
      BASHRC_FILE="$1"
      ;;
    --no-rc)
      UPDATE_BASHRC=0
      ;;
    --help)
      usage
      exit 0
      ;;
    --)
      shift
      (($# == 0)) || die "unexpected positional arguments"
      break
      ;;
    -*)
      die "unknown option: $1"
      ;;
    *)
      die "unexpected positional argument: $1"
      ;;
  esac
  shift
done

if [[ -z "${SOURCE_DIR}" ]]; then
  if [[ -d "./builtins" ]]; then
    SOURCE_DIR="./builtins"
  elif [[ -d "./build" ]]; then
    SOURCE_DIR="./build"
  else
    die "could not auto-detect source directory; use --source DIR"
  fi
fi

[[ -d "${SOURCE_DIR}" ]] || die "source directory does not exist: ${SOURCE_DIR}"

shopt -s nullglob
so_files=("${SOURCE_DIR}"/*.so)
shopt -u nullglob
(( ${#so_files[@]} > 0 )) || die "no .so files found in ${SOURCE_DIR}"

mkdir -p "${PREFIX_DIR}"
for so in "${so_files[@]}"; do
  cp -f "${so}" "${PREFIX_DIR}/"
done

loader_file="${PREFIX_DIR}/load.sh"
{
  printf '#!/usr/bin/env bash\n'
  printf '# Generated by Bash Diamonds install-user.sh\n'
  printf '%s\n' "[ -n \"\${BASH_VERSION:-}\" ] || return 0"
  printf 'for so in "%s"/*.so; do\n' "${PREFIX_DIR}"
  printf '%s\n' "  [ -f \"\$so\" ] || continue"
  printf '%s\n' "  name=\"\${so##*/}\""
  printf '%s\n' "  name=\"\${name%.so}\""
  printf '%s\n' "  enable -f \"\$so\" \"\$name\" 2>/dev/null || true"
  printf '%s\n' "done"
} > "${loader_file}"
chmod 0644 "${loader_file}"

if (( UPDATE_BASHRC )); then
  marker_start="# >>> bash-diamonds >>>"
  marker_end="# <<< bash-diamonds <<<"
  if [[ -f "${BASHRC_FILE}" ]] && grep -Fq "${marker_start}" "${BASHRC_FILE}"; then
    :
  else
    {
      printf '\n%s\n' "${marker_start}"
      printf '[ -f "%s" ] && . "%s"\n' "${loader_file}" "${loader_file}"
      printf '%s\n' "${marker_end}"
    } >> "${BASHRC_FILE}"
  fi
fi

printf 'Installed %d builtins to %s\n' "${#so_files[@]}" "${PREFIX_DIR}"
printf 'Loader script: %s\n' "${loader_file}"
if (( UPDATE_BASHRC )); then
  printf 'Bash rc updated: %s\n' "${BASHRC_FILE}"
else
  printf 'Bash rc unchanged (--no-rc)\n'
fi
