name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  conformance:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            bats \
            bash-builtins \
            build-essential

      - name: Detect bash headers
        run: |
          set -euxo pipefail
          test -d /usr/include/bash
          echo "BASH_SRC=/usr/include/bash" >> "$GITHUB_ENV"

      - name: Run conformance tests
        run: make test BASH_SRC="${BASH_SRC}"
